[pytest]
testpaths = tests features
python_files = test_*.py
python_classes = Test*
python_functions = test_*
bdd_features_base_dir = features/
markers =
       e2e: End two end
addopts = -v --tb=short --html=reports/report.html --self-contained-html
